title: klog
email: kellyjosephprice@gmail.com
description: >-
  A personal blog about web development, cats, and stuff.
baseurl: ""
url: https://kellyjosephprice.github.io
twitter_username: kjprice
github_username: kellyjosephprice

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
